Rails.application.routes.draw do
  get 'admin_panel/index'
  post 'admin_panel/index'
  get 'admin_panel/modify'
  get 'admin_panel/load'
  post 'admin_panel/load'
  get 'configuraiton/index'
  post 'configuration/index'
  get 'recommendations/list'
  get 'recommendations/new'
  get 'recommendations/show'
  get 'recommendations/edit'
  get 'recommendations/destroy'
  root 'menu#index'
  get 'menu/index'
  post 'menu/index'
  get 'data_scraper/list'
  post 'data_scraper/scrape'
  get 'student_application/index'
  post 'student_application/index'
  get 'student_application/new'
  post 'student_application/new'
  get 'student_application/create'
  post 'student_application/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
