Rails.application.routes.draw do
  devise_for :admins
  devise_for :teacher_users
  devise_for :users
  get 'admin_panel/index'
  post 'admin_panel/index'
  get 'admin_panel/modify'
  post 'admin_panel/modify'
  get 'data_scraper/organize'
  post 'data_scraper/organize'
  get 'data_scraper/load'
  post 'data_scraper/load'
  get 'configuration/index'
  post 'configuration/index'
  get 'data_scraper/collect'
  post 'data_scraper/collect'
  root 'menu#index'
  get 'menu/index'
  post 'menu/index'
  get 'data_scraper/scrape'
  post 'data_scraper/scrape'
  get 'student_application/index'
  post 'student_application/index'
  get 'student_application/new'
  post 'student_application/new'
  get 'student_application/create'
  post 'student_application/create'
  get 'student_application/show'
  get  'student_application/edit'
  get 'student_application/update'
  put 'student_application/update'
  get 'student_application/delete'
  delete 'student_application/delete'
  get 'evaluations/show'
  post 'evaluations/show'
  get 'evaluations/new'
  post 'evaluations/new'
  get 'evaluations/index'
  post 'evaluations/index'
  get 'evaluations/create'
  post 'evaluations/create'
  delete 'evaluations/index' => 'evaluations#delete'
  get 'evaluations/destroy'
  get 'evaluations/update'
  put 'evaluations/update'
  get 'evaluations/edit'


  #get '/' =>'recommendations#new'
  get 'recommendations/list'
  get 'recommendations/new'
  get 'recommendations/show'
  get 'recommendations/edit'
  get 'recommendations/destroy'
  post 'recommendations/list'
  post 'recommendations/new'
  post 'recommendations/edit'
  get 'recommendations/create'
  post 'recommendations/create'
  #get 'recommendation/show'
  post 'recommendations/show'
  post 'recommendations/create' => 'recommendations#create'
  post 'recommendations/show' => 'recommendations#show'
  delete 'recommendations/show' => 'recommendations#delete'
  post 'recommendations/show' => 'recommendations#edit'
  post 'recommendations/update' => 'recommendations#update'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'profiles/edit'

  get 'overall_login/choose_user'
  post 'overall_login/choose_user'
  get 'overall_login/choose_login'
  post 'overall_login/choose_login'
end
